baseURL = 'https://satori5ama.github.io'
languageCode = 'en-us'
title = '幻想安全区'
theme = 'yinyang'

[params]
headTitle = "幻想安全区"
mainSections = ["posts"]

[[params.socials]]
name = "About Me"
link = "https://joway.io"
[[params.socials]]
name = "Github"
link = "https://github.com/joway"

[taxonomies]
category = 'categories'
tag = 'tags'