baseURL = 'https://Satori5ama.github.io'
languageCode = 'en-us'
title = '幻想安全区'
theme = 'yinyang'


[params]
headTitle = "幻想安全区 —— Shy's Blog"
mainSections = ["posts"]

[[params.socials]]
name = "Introduction"
link = "https://Satori5ama.github.io/posts/introduction"
[[params.socials]]
name = "Catalogue"
link = "https://satori5ama.github.io/tags/%E6%96%87%E7%AB%A0%E5%88%97%E8%A1%A8/"
[[params.socials]]
name = "About"
link = "https://Satori5ama.github.io/posts/about-me/"
[[params.socials]]
name = "Luogu"
link = "https://www.luogu.com.cn/user/72462"
[[params.socials]]
name = "Github"
link = "https://github.com/Satori5ama"

[taxonomies]
category = 'categories'
tag = 'tags'

[author]
  name = "Shy"
  homepage = "https://Satori5ama.github.io/posts/about-me/"
