baseURL = 'https://Satori5ama.github.io'
languageCode = 'en-us'
title = '幻想安全区 - Satori5ama - 博客'
theme = 'yinyang'
#logo = "img/luckyblock.jpg"
#svgFavicon = "img/luckyblock.svg"
#avatarURL = "img/luckyblock.jpg"

[params]
headTitle = "幻想安全区 ~ Dreamscape Haven"
mainSections = ["posts"]
Description="我们称之为路的，其实不过是彷徨。"
Favicon = "/img/satori.svg"
#extraCSSFiles = ["/css/friend.css", "css/bar.css"]

[[params.socials]]
name = "站点介绍"
link = "/introduction/"
[[params.socials]]
name = "归档"
link = "/posts/"
[[params.socials]]
name = "关于"
link = "/about/"
[[params.socials]]
name = "友链"
link = "/friend/"
[[params.socials]]
name = "洛谷"
link = "https://www.luogu.com.cn/user/72462"
[[params.socials]]
name = "Github"
link = "https://github.com/Satori5ama"

[taxonomies]
category = 'categories'
tag = 'tags'

[author]
  name = "Satori5ama"
  homepage = "/about/"


# 添加不蒜子计数
[params.busuanzi]
  enable = true
  # 是否开启全站独立访客数
  site_uv = true
  # 全站独立访客数前的图标或提示语
  site_uv_pre = '<i class="fa fa-user"></i>' 
  # 全站独立访客数后的图标或提示语
  site_uv_post = ''
  # 是否开启全站浏览量
  site_pv = true
  # 全站浏览量前的图标或提示语
  site_pv_pre = '<i class="fa fa-eye"></i>'
  # 全站浏览量后的图标或提示语
  site_pv_post = ''
  # 是否开启单页浏览量
  page_pv = true
  # 单页浏览量前的图标或提示语
  page_pv_pre = '<i class="far fa-eye fa-fw"></i>'
  # 单页浏览量后的图标或提示语
  page_pv_post = ''

