baseURL = 'https://Satori5ama.github.io'
languageCode = 'en-us'
title = '幻想安全区'
theme = 'yinyang'


[params]
headTitle = "幻想安全区 —— Shy's Blog"
mainSections = ["posts"]




[[params.socials]]
name = "站点介绍"
link = "https://Satori5ama.github.io/introduction/"
[[params.socials]]
name = "归档"
link = "https://satori5ama.github.io/tags/%E6%96%87%E7%AB%A0%E5%88%97%E8%A1%A8/"
[[params.socials]]
name = "关于"
link = "https://Satori5ama.github.io/about/"
[[params.socials]]
name = "日志"
link = "https://github.com/Satori5ama/Satori5ama.github.io/blob/main/README.md"
[[params.socials]]
name = "洛谷"
link = "https://www.luogu.com.cn/user/72462"
[[params.socials]]
name = "Github"
link = "https://github.com/Satori5ama"

[taxonomies]
category = 'categories'
tag = 'tags'

[author]
  name = "Shy"
  homepage = "https://Satori5ama.github.io/posts/about-me/"
